global:
  scrape_interval: "30s"

scrape_configs:
  - job_name: "node-prometheus-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:9100"]
        labels:
          source: "node-prometheus-exporter"

  - job_name: "vaillant-poller"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["vaillant-poller:9200"]
        labels:
          source: "vaillant-poller"
